// Auto-generated by the SPA converter.
// Stubs @tanstack/react-start so SSR features compile but do nothing at runtime.
/* eslint-disable @typescript-eslint/no-explicit-any */

type AnyFn = (...args: any[]) => any;

function makeBuilder(): any {
  const builder: any = {};
  builder.middleware = () => builder;
  builder.inputValidator = () => builder;
  builder.validator = () => builder;
  builder.handler = (_fn: AnyFn) => {
    const stub = async (_args?: any) => ({} as any);
    (stub as any).url = "";
    return stub;
  };
  return builder;
}

export function createServerFn(_opts?: any) { return makeBuilder(); }
export function createMiddleware(_opts?: any) {
  const mw: any = {};
  mw.server = () => mw;
  mw.client = () => mw;
  mw.middleware = () => mw;
  return mw;
}
export function createIsomorphicFn() {
  const iso: any = {};
  const noop = () => undefined;
  iso.server = () => noop;
  iso.client = () => noop;
  return iso;
}
export function createStart(_factory?: any) {
  return { addMiddleware: () => undefined };
}
export function useServerFn<T extends AnyFn>(fn: T): T {
  return fn;
}
export const startInstance: any = { addMiddleware: () => undefined };
