/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaysSlugRouteImport } from './routes/plays.$slug'
import { Route as PlaysSlugCharacterCharSlugRouteImport } from './routes/plays.$slug_.character.$charSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysSlugRoute = PlaysSlugRouteImport.update({
  id: '/plays/$slug',
  path: '/plays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysSlugCharacterCharSlugRoute =
  PlaysSlugCharacterCharSlugRouteImport.update({
    id: '/plays/$slug_/character/$charSlug',
    path: '/plays/$slug/character/$charSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plays/$slug': typeof PlaysSlugRoute
  '/plays/$slug/character/$charSlug': typeof PlaysSlugCharacterCharSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plays/$slug': typeof PlaysSlugRoute
  '/plays/$slug/character/$charSlug': typeof PlaysSlugCharacterCharSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plays/$slug': typeof PlaysSlugRoute
  '/plays/$slug_/character/$charSlug': typeof PlaysSlugCharacterCharSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plays/$slug' | '/plays/$slug/character/$charSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plays/$slug' | '/plays/$slug/character/$charSlug'
  id: '__root__' | '/' | '/plays/$slug' | '/plays/$slug_/character/$charSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaysSlugRoute: typeof PlaysSlugRoute
  PlaysSlugCharacterCharSlugRoute: typeof PlaysSlugCharacterCharSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$slug': {
      id: '/plays/$slug'
      path: '/plays/$slug'
      fullPath: '/plays/$slug'
      preLoaderRoute: typeof PlaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$slug_/character/$charSlug': {
      id: '/plays/$slug_/character/$charSlug'
      path: '/plays/$slug/character/$charSlug'
      fullPath: '/plays/$slug/character/$charSlug'
      preLoaderRoute: typeof PlaysSlugCharacterCharSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaysSlugRoute: PlaysSlugRoute,
  PlaysSlugCharacterCharSlugRoute: PlaysSlugCharacterCharSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
