/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NatokIndexRouteImport } from './routes/natok.index'
import { Route as NatokSlugRouteImport } from './routes/natok.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NatokIndexRoute = NatokIndexRouteImport.update({
  id: '/natok/',
  path: '/natok/',
  getParentRoute: () => rootRouteImport,
} as any)
const NatokSlugRoute = NatokSlugRouteImport.update({
  id: '/natok/$slug',
  path: '/natok/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/natok/$slug': typeof NatokSlugRoute
  '/natok/': typeof NatokIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/natok/$slug': typeof NatokSlugRoute
  '/natok': typeof NatokIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/natok/$slug': typeof NatokSlugRoute
  '/natok/': typeof NatokIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/natok/$slug' | '/natok/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/natok/$slug' | '/natok'
  id: '__root__' | '/' | '/sitemap.xml' | '/natok/$slug' | '/natok/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  NatokSlugRoute: typeof NatokSlugRoute
  NatokIndexRoute: typeof NatokIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natok/': {
      id: '/natok/'
      path: '/natok'
      fullPath: '/natok/'
      preLoaderRoute: typeof NatokIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natok/$slug': {
      id: '/natok/$slug'
      path: '/natok/$slug'
      fullPath: '/natok/$slug'
      preLoaderRoute: typeof NatokSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  NatokSlugRoute: NatokSlugRoute,
  NatokIndexRoute: NatokIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
