name: build
on:
  workflow_dispatch:
    inputs:
      job_id:
        required: true
        description: Build job id
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --no-audit --no-fund
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ inputs.job_id }}
          path: dist
